wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: huggingface
    huggingface_version: 4.21.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1670885325.378728
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 40
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 40
      - 49
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.6
      6: 4.21.3
      8:
      - 4
      - 5
